### ISSUE TITLE
 Robustness Against Post-Processing Augmentations - Gaussian Noise Impact on SDv1.5 Model: Threshold Recalculation Needed?

### ISSUE THREAD

**Issue by KevinWangHP** [ZhentingWang/LatentTracer#2]
In Table 9, while assessing model robustness against post-processing augmentations, an issue emerged when distinguishing between SDv2 and SDv1.5 generated images using SDv15 as inspected model. Adding Gaussian noise with a standard deviation of 0.01 to SDv1.5 images resulted in PSNR around 40, SSIM around 0.96 and reconstructed losses around 1e-4, which exceeds the threshold of 5e-5. This discrepancy led to zero correct identifications for SDv1.5, conflicting with the reported accuracy of 0.97.

I was wondering about the experiment details. Should the threshold be adjusted when noise is added? Specifically, should noise also be applied to the generated images used to compute this threshold?

**Comment by ZhentingWang** [comment]
Thank you very much for your message. Yes, the setting here is recalculating the threshold using the augmentations.
