### ISSUE TITLE
和DIRE的区别？

### ISSUE THREAD

**Issue by Jmh0527** [ZhentingWang/LatentTracer#3]
您好，我想请教一下论文中的方案和DIRE相比，不同之处或者说优势的地方在哪里呢？

**Comment by ZhentingWang** [comment]
您好，我们所解决的问题和dire不一样，dire是检测一个图片是ai生成的还是真实的。我们的问题是给定一个模型和图片，判断这个图片是这个模型生成的还是来自其他来源（真实图片或其他模型生成的）。
